Repository astarte-platform/astarte_core, pull requests merged in 2020-01, with the labels that each got.

#11 Handle empty binary as bson_value when encoding events
  CHANGELOG.md
  lib/astarte_core/triggers/simple_events/encoder.ex
  test/astarte_core/triggers/simple_events_encoder_test.exs
Labels: bug

#12 simple_trigger_config: allow * interface only on incoming_data triggers
  CHANGELOG.md
  lib/astarte_core/triggers/simple_trigger_config.ex
  test/astarte_core/triggers/simple_trigger_config_test.exs
Labels: API

#10 Allow hyphens in interface_name
  CHANGELOG.md
  lib/astarte_core/cql_utils.ex
  lib/astarte_core/interface.ex
  test/astarte_core/interface_test.exs
Labels: enhancement

#13 interface: update interface name pattern in interface schema
  specs/interface.json
Labels: enhancement, user experience

#15 Prepare 0.11.0-beta.2
  CHANGELOG.md
  mix.exs
Labels: chore
