Repository astarte-platform/astarte_core, pull requests merged in 2020-02, with the labels that each got.

#16 Add support for aggregated server owned interfaces
  CHANGELOG.md
  lib/astarte_core/interface.ex
  mix.exs
  test/astarte_core/interface_test.exs
Labels: enhancement, main feature

#18 Prepare new development cycle
  .gitlab-ci.yml
  .travis.yml
  CHANGELOG.md
  mix.exs
  mix.lock
Labels: chore

#17 Fix parametric automaton transitions
  CHANGELOG.md
  lib/astarte_core/mapping.ex
  lib/astarte_core/mapping/endpoints_automaton.ex
  test/astarte_core/mapping/endpoints_automaton_test.exs
Labels: bug

#21 Repo housekeeping: actions and DCO
  .github/dco.yml
  .github/workflows/build-workflow.yaml
  .gitlab-ci.yml
  .travis.yml
Labels: chore
