Repository astarte-platform/astarte_core, pull requests merged in 2020-08, with the labels that each got.

#42 Retrieve doc and description from db result
  lib/astarte_core/mapping.ex
  test/astarte_core/mapping_test.exs
Labels: chore, minor

#41 Handle missing endpoint in mapping
  CHANGELOG.md
  lib/astarte_core/interface.ex
Labels: bug, user experience

#38 Fix Ecto.Type warnings
  lib/astarte_core/interface/aggregation.ex
  lib/astarte_core/interface/ownership.ex
  lib/astarte_core/interface/type.ex
  lib/astarte_core/mapping/database_retention_policy.ex
  lib/astarte_core/mapping/reliability.ex
  lib/astarte_core/mapping/retention.ex
  lib/astarte_core/mapping/value_type.ex
  lib/astarte_core/storage_type.ex
Labels: chore

#43 Avoid failed check status on GitHub PR due to codecov bogus coverage
  codecov.yaml
Labels: chore

#44 Update version number to 0.11.2
  .github/workflows/build-workflow.yaml
  .tool-versions
  CHANGELOG.md
  mix.exs
Labels: chore
