Repository astarte-platform/astarte_core, pull requests merged in 2020-06, with the labels that each got.

#34 Update deps and start using OTP23
  .github/workflows/build-workflow.yaml
  .tool-versions
  mix.lock
Labels: chore

#33 Add support for device-specific and group-specific triggers
  CHANGELOG.md
  lib/astarte_core/triggers/simple_trigger_config.ex
  lib/astarte_core/triggers/simple_triggers_protobuf/data_trigger.proto
  lib/astarte_core/triggers/simple_triggers_protobuf/device_trigger.proto
  lib/astarte_core/triggers/simple_triggers_protobuf/utils.ex
  mix.exs
  mix.lock
  test/astarte_core/triggers/simple_trigger_config_test.exs
Labels: enhancement, main feature, user experience

#35 Update GitHub build-workflow
  .github/workflows/build-workflow.yaml
Labels: chore

#37 Add DeviceErrorEvent
  CHANGELOG.md
  lib/astarte_core/triggers/simple_events/device_error_event.proto
  lib/astarte_core/triggers/simple_events/encoder.ex
  lib/astarte_core/triggers/simple_events/simple_event.proto
  test/astarte_core/triggers/simple_events_encoder_test.exs
Labels: enhancement, main feature

#39 Prepare 1.0.0-alpha.1
  CHANGELOG.md
  mix.exs
Labels: chore
